# Generated by Django 5.0.1 on 2024-01-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qustions',
            new_name='Question',
        ),
    ]
